#!/usr/bin/env php
<?php

include "src/Dates/BirthDays.php";

$opts = getopt("b::");
$birthDate = $opts["b"] ?? "1992-10-11";

$days = new \Lytvyn\Dates\BirthDays($birthDate);

echo "$birthDate: {$days->findTotalDays()}\n";